#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
# nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &
#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH
set -x

export JAVA_HOME=$OPENSHIFT_DATA_DIR'jdk1.8.0_20'
export PATH=$JAVA_HOME/bin:$PATH
echo "Entering  $OPENSHIFT_REPO_DIR to start server"
cd $OPENSHIFT_REPO_DIR

echo "Running jar command"
nohup java -Xms384m -Xmx412m -jar build/libs/*.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} --spring.profiles.active=openshift &
